-- H2 兼容测试 Schema（ENUM → VARCHAR, JSON → TEXT）
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  openid VARCHAR(64) NOT NULL,
  nickname VARCHAR(64) DEFAULT NULL,
  avatar_url VARCHAR(256) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  member_type VARCHAR(16) DEFAULT 'normal',
  member_expire_time DATETIME DEFAULT NULL,
  points INT DEFAULT 0,
  download_count INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY idx_users_openid (openid)
);

CREATE TABLE IF NOT EXISTS materials (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL,
  description VARCHAR(1000),
  image_url VARCHAR(256) NOT NULL,
  thumbnail_url VARCHAR(256) DEFAULT NULL,
  category VARCHAR(32) DEFAULT NULL,
  material_type VARCHAR(16) NOT NULL DEFAULT 'single',
  issue_year INT DEFAULT NULL,
  issue_number INT DEFAULT NULL,
  tags VARCHAR(500) DEFAULT NULL,
  is_premium TINYINT DEFAULT 0,
  download_count INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  sort_order INT DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS redeem_codes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(32) NOT NULL,
  type VARCHAR(16) NOT NULL,
  status TINYINT DEFAULT 0,
  user_id BIGINT DEFAULT NULL,
  used_time DATETIME DEFAULT NULL,
  expire_time DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY idx_redeem_codes_code (code),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS downloads (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL,
  downloaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY idx_downloads_user_material (user_id, material_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tools (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(128) DEFAULT NULL,
  icon VARCHAR(16) DEFAULT NULL,
  url VARCHAR(256) NOT NULL,
  category VARCHAR(32) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_default TINYINT NOT NULL DEFAULT 0,
  user_id BIGINT DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL,
  type VARCHAR(16) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_categories_name_type (name, type)
);

CREATE TABLE IF NOT EXISTS text_assets (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  content TEXT NOT NULL,
  content_hash CHAR(64) NOT NULL,
  type VARCHAR(16) NOT NULL,
  category VARCHAR(32) NOT NULL,
  tags VARCHAR(4000) DEFAULT NULL,
  source VARCHAR(32) NOT NULL DEFAULT 'manual',
  source_url VARCHAR(512) DEFAULT NULL,
  risk_level VARCHAR(16) NOT NULL DEFAULT 'safe',
  status TINYINT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_text_assets_content_hash (content_hash)
);

CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY idx_favorites_user_material (user_id, material_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feedbacks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT DEFAULT NULL,
  content TEXT NOT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS wechat_message_probe (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  msg_id VARCHAR(64) DEFAULT NULL,
  delivery_key CHAR(64) NOT NULL,
  from_openid VARCHAR(128),
  to_username VARCHAR(128),
  message_create_time BIGINT,
  msg_type VARCHAR(32),
  event_type VARCHAR(64),
  event_key VARCHAR(256),
  media_id VARCHAR(256),
  pic_url VARCHAR(1024),
  content VARCHAR(2048),
  format VARCHAR(32),
  recognition VARCHAR(2048),
  raw_xml TEXT NOT NULL,
  signature_valid TINYINT NOT NULL DEFAULT 1,
  download_status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
  download_http_status INT,
  download_error VARCHAR(1000),
  detected_file_type VARCHAR(16),
  detected_mime_type VARCHAR(64),
  file_size BIGINT,
  width INT,
  height INT,
  is_animated TINYINT,
  frame_count INT,
  file_sha256 CHAR(64),
  probe_object_key VARCHAR(512),
  trace_id VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (msg_id),
  UNIQUE (delivery_key)
);

CREATE TABLE IF NOT EXISTS aura_templates (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  template_key VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  style VARCHAR(32) NOT NULL,
  preview_url VARCHAR(512),
  supported_ratios VARCHAR(1000) NOT NULL,
  config_json CLOB NOT NULL,
  config_version INT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aura_templates_key (template_key)
);

CREATE TABLE IF NOT EXISTS aura_assets (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  asset_key VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(16) NOT NULL,
  file_url VARCHAR(512) NOT NULL,
  preview_url VARCHAR(512),
  sha256 CHAR(64) NOT NULL,
  resource_version INT NOT NULL DEFAULT 1,
  metadata_json CLOB,
  status TINYINT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aura_assets_key (asset_key)
);
