CREATE TABLE IF NOT EXISTS `text_decoration_templates` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `category` VARCHAR(24) NOT NULL,
  `type` VARCHAR(16) NOT NULL,
  `prefix` TEXT DEFAULT NULL,
  `suffix` TEXT DEFAULT NULL,
  `template` TEXT DEFAULT NULL,
  `preview_text` VARCHAR(64) NOT NULL DEFAULT 'hello',
  `unicode_level` VARCHAR(16) NOT NULL DEFAULT 'standard',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_text_decoration_name` (`name`),
  KEY `idx_text_decoration_public` (`enabled`, `category`, `sort_order`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO text_decoration_templates
(name, category, type, prefix, suffix, template, preview_text, unicode_level, enabled, sort_order) VALUES
('Soft Heart', 'heart', 'inline', '♡ ', ' ♡', NULL, 'hello', 'basic', 1, 1),
('Bold Heart', 'heart', 'inline', '♥ ', ' ♥', NULL, 'hello', 'basic', 1, 2),
('Sugar Heart', 'heart', 'inline', '♡₊˚ ', ' ˚₊♡', NULL, 'hello', 'standard', 1, 3),
('Quoted Heart', 'heart', 'inline', '˗ˏˋ ♡ ', ' ♡ ˎˊ˗', NULL, 'hello', 'standard', 1, 4),
('Heart Cradle', 'heart', 'inline', '꒰ ♡ ', ' ♡ ꒱', NULL, 'hello', 'extended', 1, 5),
('Tiny Hearts', 'heart', 'inline', '♡⃛ ', ' ♡⃛', NULL, 'hello', 'extended', 1, 6),
('Halo Heart', 'heart', 'inline', '₊˚⊹♡ ', ' ♡⊹˚₊', NULL, 'hello', 'standard', 1, 7),
('Heartbeat', 'heart', 'inline', '♡— ', ' —♡', NULL, 'hello', 'basic', 1, 8),
('Heart Spark', 'heart', 'inline', '✧♡ ', ' ♡✧', NULL, 'hello', 'basic', 1, 9),
('Heart Frame', 'heart', 'multiline', '','', '┈┈୨♡୧┈┈\n{text}\n┈┈୨♡୧┈┈', 'hello', 'extended', 1, 10),

('Classic Star', 'star', 'inline', '☆ ', ' ☆', NULL, 'hello', 'basic', 1, 11),
('Star Degree', 'star', 'inline', '☆° ', ' °☆', NULL, 'hello', 'basic', 1, 12),
('Four Point', 'star', 'inline', '✦ ', ' ✦', NULL, 'hello', 'basic', 1, 13),
('Light Star', 'star', 'inline', '✧ ', ' ✧', NULL, 'hello', 'basic', 1, 14),
('Little Star', 'star', 'inline', '⋆ ', ' ⋆', NULL, 'hello', 'standard', 1, 15),
('Galaxy Star', 'star', 'inline', '⋆｡°✩ ', ' ✩°｡⋆', NULL, 'hello', 'standard', 1, 16),
('Rising Star', 'star', 'inline', '✩₊˚ ', ' ˚₊✩', NULL, 'hello', 'standard', 1, 17),
('Y2K Star', 'star', 'inline', '★彡 ', ' 彡★', NULL, 'hello', 'standard', 1, 18),
('Star Trail', 'star', 'inline', '✦•┈ ', ' ┈•✦', NULL, 'hello', 'basic', 1, 19),
('Starlight', 'star', 'inline', '⋆⁺₊⋆ ', ' ⋆⁺₊⋆', NULL, 'hello', 'standard', 1, 20),

('Cloud Angel', 'dreamy', 'inline', '˚₊‧꒰ა ', ' ໒꒱ ‧₊˚', NULL, 'hello', 'extended', 1, 21),
('Dream Orbit', 'dreamy', 'inline', '⋆ ˚｡⋆୨ ', ' ୧⋆ ˚｡⋆', NULL, 'hello', 'extended', 1, 22),
('Soft Cloud', 'dreamy', 'inline', '☁︎ ', ' ☁︎', NULL, 'hello', 'standard', 1, 23),
('Dream Dust', 'dreamy', 'inline', '₊˚⊹ ', ' ⊹˚₊', NULL, 'hello', 'standard', 1, 24),
('Fairy Trace', 'dreamy', 'inline', '𓂃 ࣪˖ ִֶָ ', ' ִֶָ˖ ࣪𓂃', NULL, 'hello', 'extended', 1, 25),
('Moon Dream', 'dreamy', 'inline', '☾⋆ ', ' ⋆☽', NULL, 'hello', 'standard', 1, 26),
('Twilight', 'dreamy', 'inline', '˖⁺‧₊˚ ', ' ˚₊‧⁺˖', NULL, 'hello', 'standard', 1, 27),
('Angel Wing', 'dreamy', 'inline', 'ʚ ', ' ɞ', NULL, 'hello', 'standard', 1, 28),
('Bubble Dream', 'dreamy', 'inline', '｡ﾟ･ ', ' ･ﾟ｡', NULL, 'hello', 'basic', 1, 29),
('Dream Window', 'dreamy', 'multiline', '', '', '☁︎⋆｡ ﾟ☾ ﾟ｡⋆\n{text}\n⋆｡ ﾟ☁︎ ﾟ｡⋆', 'hello', 'standard', 1, 30),

('Classic Ribbon', 'ribbon', 'inline', '୨୧ ', ' ୨୧', NULL, 'hello', 'standard', 1, 31),
('Sugar Ribbon', 'ribbon', 'inline', '୨୧₊˚ ', ' ˚₊୨୧', NULL, 'hello', 'standard', 1, 32),
('Angel Ribbon', 'ribbon', 'inline', '꒰ა ', ' ໒꒱', NULL, 'hello', 'extended', 1, 33),
('Tiny Bow', 'ribbon', 'inline', '𐙚 ', ' 𐙚', NULL, 'hello', 'extended', 1, 34),
('Bow Sparkle', 'ribbon', 'inline', '⋆౨ৎ˚⟡˖ ', ' ˖⟡˚౨ৎ⋆', NULL, 'hello', 'extended', 1, 35),
('Ribbon Line', 'ribbon', 'inline', '୨୧ ─ ', ' ─ ୨୧', NULL, 'hello', 'standard', 1, 36),
('Double Bow', 'ribbon', 'inline', '౨ৎ ', ' ౨ৎ', NULL, 'hello', 'extended', 1, 37),
('Bow Quote', 'ribbon', 'inline', '˗ˏˋ ୨୧ ', ' ୨୧ ˎˊ˗', NULL, 'hello', 'standard', 1, 38),
('Ribbon Beads', 'ribbon', 'inline', '୨୧•° ', ' °•୨୧', NULL, 'hello', 'standard', 1, 39),
('Ribbon Frame', 'ribbon', 'multiline', '', '', '╭─୨୧─╮\n{text}\n╰─୨୧─╯', 'hello', 'standard', 1, 40),

('Daisy', 'flower', 'inline', '✿ ', ' ✿', NULL, 'hello', 'basic', 1, 41),
('Blossom', 'flower', 'inline', '❀ ', ' ❀', NULL, 'hello', 'basic', 1, 42),
('Flower Wheel', 'flower', 'inline', '✽ ', ' ✽', NULL, 'hello', 'basic', 1, 43),
('Little Bloom', 'flower', 'inline', '❁ ', ' ❁', NULL, 'hello', 'basic', 1, 44),
('Tulip', 'flower', 'inline', '🌷 ', ' 🌷', NULL, 'hello', 'emoji', 1, 45),
('Sugar Blossom', 'flower', 'inline', '❀₊˚ ', ' ˚₊❀', NULL, 'hello', 'standard', 1, 46),
('Petal Trail', 'flower', 'inline', '༺❀༻ ', ' ༺❀༻', NULL, 'hello', 'standard', 1, 47),
('Pressed Flower', 'flower', 'inline', '𓆸 ', ' 𓆸', NULL, 'hello', 'extended', 1, 48),
('Flower Garden', 'flower', 'inline', '✿❀ ', ' ❀✿', NULL, 'hello', 'basic', 1, 49),
('Flower Frame', 'flower', 'multiline', '', '', '❀。• *₊°。 ❀°。\n{text}\n❀。• *₊°。 ❀°。', 'hello', 'standard', 1, 50),

('Forest Seed', 'plant', 'inline', '𖥧 ', ' 𖥧', NULL, 'hello', 'extended', 1, 51),
('Forest Sprout', 'plant', 'inline', '𖤣 ', ' 𖤣', NULL, 'hello', 'extended', 1, 52),
('Lucky Clover', 'plant', 'inline', '☘ ', ' ☘', NULL, 'hello', 'basic', 1, 53),
('Vine', 'plant', 'inline', '❦ ', ' ❦', NULL, 'hello', 'basic', 1, 54),
('Leaf Breeze', 'plant', 'inline', '༄ ', ' ༄', NULL, 'hello', 'standard', 1, 55),
('Wildflower', 'plant', 'inline', '𓆸 ', ' 𓆸', NULL, 'hello', 'extended', 1, 56),
('Leaf Pair', 'plant', 'inline', 'ꕤ ', ' ꕤ', NULL, 'hello', 'extended', 1, 57),
('Garden Line', 'plant', 'inline', '𖡼.𖤣𖥧 ', ' 𖥧𖤣.𖡼', NULL, 'hello', 'extended', 1, 58),
('Fern', 'plant', 'inline', '𓇢𓆸 ', ' 𓆸𓇢', NULL, 'hello', 'extended', 1, 59),
('Greenhouse', 'plant', 'inline', '⌇𓂃🌿 ', ' 🌿𓂃⌇', NULL, 'hello', 'emoji', 1, 60),

('Retro Spark', 'y2k', 'inline', '☆.｡.:* ', ' *:.｡.☆', NULL, 'hello', 'basic', 1, 61),
('Internet Angel', 'y2k', 'inline', '✧･ﾟ: * ', ' *:･ﾟ✧', NULL, 'hello', 'basic', 1, 62),
('Pop Star', 'y2k', 'inline', '★ ', ' ★', NULL, 'hello', 'basic', 1, 63),
('Heart Underscore', 'y2k', 'inline', '♡_', '_♡', NULL, 'hello', 'basic', 1, 64),
('Tilde Pop', 'y2k', 'inline', '~* ', ' *~', NULL, 'hello', 'basic', 1, 65),
('Cyber Bracket', 'y2k', 'inline', '[x] ', ' [x]', NULL, 'hello', 'basic', 1, 66),
('Pixel Love', 'y2k', 'inline', '<3:: ', ' ::<3', NULL, 'hello', 'basic', 1, 67),
('Online Now', 'y2k', 'inline', '°º¤ø,¸ ', ' ¸,ø¤º°', NULL, 'hello', 'standard', 1, 68),
('Glitter Web', 'y2k', 'inline', '×º°”˜`”°º× ', ' ×º°”˜`”°º×', NULL, 'hello', 'standard', 1, 69),
('Chatroom', 'y2k', 'inline', '»»—— ', ' ——««', NULL, 'hello', 'basic', 1, 70),

('Long Dash', 'minimal', 'inline', '— ', ' —', NULL, 'hello', 'basic', 1, 71),
('Bullet', 'minimal', 'inline', '• ', ' •', NULL, 'hello', 'basic', 1, 72),
('Middle Dot', 'minimal', 'inline', '· ', ' ·', NULL, 'hello', 'basic', 1, 73),
('Square Bracket', 'minimal', 'inline', '[ ', ' ]', NULL, 'hello', 'basic', 1, 74),
('Round Bracket', 'minimal', 'inline', '( ', ' )', NULL, 'hello', 'basic', 1, 75),
('Japanese Quote', 'minimal', 'inline', '「 ', ' 」', NULL, 'hello', 'basic', 1, 76),
('Angle Quote', 'minimal', 'inline', '〈 ', ' 〉', NULL, 'hello', 'basic', 1, 77),
('Slash', 'minimal', 'inline', '/ ', ' /', NULL, 'hello', 'basic', 1, 78),
('Thin Line', 'minimal', 'inline', '─ ', ' ─', NULL, 'hello', 'basic', 1, 79),
('Spaced Dot', 'minimal', 'replace', '', '', ' · ', 'hello', 'basic', 1, 80),

('Heart Box', 'frame', 'multiline', '', '', '╭──♡──╮\n{text}\n╰──♡──╯', 'hello', 'standard', 1, 81),
('Clean Box', 'frame', 'multiline', '', '', '┌────────┐\n{text}\n└────────┘', 'hello', 'basic', 1, 82),
('Double Box', 'frame', 'multiline', '', '', '╔════════╗\n{text}\n╚════════╝', 'hello', 'basic', 1, 83),
('Dotted Box', 'frame', 'multiline', '', '', '┈┈┈┈┈┈┈┈\n{text}\n┈┈┈┈┈┈┈┈', 'hello', 'standard', 1, 84),
('Corner Box', 'frame', 'multiline', '', '', '⌜       ⌝\n{text}\n⌞       ⌟', 'hello', 'basic', 1, 85),
('Flower Box', 'frame', 'multiline', '', '', '╭─❀─╮\n{text}\n╰─❀─╯', 'hello', 'basic', 1, 86),
('Star Box', 'frame', 'multiline', '', '', '┏━☆━┓\n{text}\n┗━☆━┛', 'hello', 'basic', 1, 87),
('Cloud Box', 'frame', 'multiline', '', '', '☁︎ ┈┈┈ ☁︎\n{text}\n☁︎ ┈┈┈ ☁︎', 'hello', 'standard', 1, 88),
('Wave Box', 'frame', 'multiline', '', '', '～～～～～～\n{text}\n～～～～～～', 'hello', 'basic', 1, 89),
('Tiny Frame', 'frame', 'inline', '〔 ', ' 〕', NULL, 'hello', 'basic', 1, 90),

('Heart Divider', 'divider', 'inline', '♡ ───── ', ' ───── ♡', NULL, 'hello', 'basic', 1, 91),
('Star Divider', 'divider', 'inline', '✦ ┈┈ ', ' ┈┈ ✦', NULL, 'hello', 'standard', 1, 92),
('Dust Divider', 'divider', 'inline', '⋆｡˚ ', ' ˚｡⋆', NULL, 'hello', 'standard', 1, 93),
('Ribbon Divider', 'divider', 'inline', '୨୧ ─ ', ' ─ ୨୧', NULL, 'hello', 'standard', 1, 94),
('Dot Divider', 'divider', 'inline', '• ─ • ', ' • ─ •', NULL, 'hello', 'basic', 1, 95),
('Flower Divider', 'divider', 'inline', '❀ ┈┈┈ ', ' ┈┈┈ ❀', NULL, 'hello', 'basic', 1, 96),
('Wave Divider', 'divider', 'inline', '〰〰 ', ' 〰〰', NULL, 'hello', 'basic', 1, 97),
('Heart Join', 'divider', 'replace', '', '', ' ♡ ', 'hello', 'basic', 1, 98),
('Star Join', 'divider', 'replace', '', '', ' ✦ ', 'hello', 'basic', 1, 99),
('Ribbon Join', 'divider', 'replace', '', '', ' ୨୧ ', 'hello', 'standard', 1, 100),
('Flower Join', 'divider', 'replace', '', '', ' ✿ ', 'hello', 'basic', 1, 101),
('Dot Join', 'divider', 'replace', '', '', ' • ', 'hello', 'basic', 1, 102);
