CREATE TABLE IF NOT EXISTS `wechat_message_probe` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `msg_id` VARCHAR(64) NULL COMMENT '微信消息ID',
  `delivery_key` CHAR(64) NOT NULL COMMENT '回调幂等键',
  `from_openid` VARCHAR(128) NULL COMMENT '发送方OpenID',
  `to_username` VARCHAR(128) NULL COMMENT '公众号原始ID',
  `message_create_time` BIGINT NULL COMMENT '微信消息创建时间戳',
  `msg_type` VARCHAR(32) NULL COMMENT '消息类型',
  `event_type` VARCHAR(64) NULL COMMENT '事件类型',
  `event_key` VARCHAR(256) NULL COMMENT '事件键',
  `media_id` VARCHAR(256) NULL COMMENT '临时素材ID',
  `pic_url` VARCHAR(1024) NULL COMMENT '图片地址',
  `content` VARCHAR(2048) NULL COMMENT '文本内容',
  `format` VARCHAR(32) NULL COMMENT '微信上报格式',
  `recognition` VARCHAR(2048) NULL COMMENT '语音识别结果',
  `raw_xml` TEXT NOT NULL COMMENT '原始明文回调XML',
  `signature_valid` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '签名是否有效',
  `download_status` VARCHAR(32) NOT NULL DEFAULT 'RECEIVED' COMMENT '处理状态',
  `download_http_status` INT NULL COMMENT '素材下载HTTP状态',
  `download_error` VARCHAR(1000) NULL COMMENT '处理失败原因',
  `detected_file_type` VARCHAR(16) NULL COMMENT '实际文件类型',
  `detected_mime_type` VARCHAR(64) NULL COMMENT '实际MIME类型',
  `file_size` BIGINT NULL COMMENT '文件字节数',
  `width` INT NULL COMMENT '图片宽度',
  `height` INT NULL COMMENT '图片高度',
  `is_animated` TINYINT(1) NULL COMMENT '是否为动画',
  `frame_count` INT NULL COMMENT '帧数',
  `file_sha256` CHAR(64) NULL COMMENT '原始文件SHA-256',
  `probe_object_key` VARCHAR(512) NULL COMMENT 'MinIO验证对象路径',
  `trace_id` VARCHAR(64) NOT NULL COMMENT '日志追踪ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wechat_probe_msg_id` (`msg_id`),
  UNIQUE KEY `uk_wechat_probe_delivery_key` (`delivery_key`),
  KEY `idx_wechat_probe_created_at` (`created_at`),
  KEY `idx_wechat_probe_status` (`download_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='微信公众号消息能力验证记录';
